- name: Clone Cadasta database repository
  become: yes
  become_user: ckan
  git: repo=https://github.com/Cadasta/cadasta-db
       dest=/opt/cadasta/cadasta-db

- name: Clone Cadasta API repository
  become: yes
  become_user: ckan
  git: repo=https://github.com/Cadasta/cadasta-api
       dest=/opt/cadasta/cadasta-api
