- name: Clone Cadasta database repository
  become: yes
  become_user: ckan
  git: repo=https://github.com/Cadasta/cadasta-db
       dest=/opt/cadasta/cadasta-db
       force=yes

- name: Clone Cadasta API repository
  become: yes
  become_user: ckan
  git: repo=https://github.com/Cadasta/cadasta-api
       dest=/opt/cadasta/cadasta-api
       force=yes

- name: Set up API settings files
  become: yes
  become_user: ckan
  template: src=settings.js
            dest=/opt/cadasta/cadasta-api/app/settings/settings.js
            owner=ckan

- name: Set up API environment settings files
  become: yes
  become_user: ckan
  template: src=environment-settings.js
            dest=/opt/cadasta/cadasta-api/app/settings/environment-settings.js
            owner=ckan

- name: Build API
  become: yes
  become_user: ckan
  script: build-api.sh

- name: Install extra API Python dependencies
  become: yes
  become_user: root
  pip: requirements=/opt/cadasta/cadasta-api/node_modules/cadasta-provider-ona/requirements.txt

- name: Delete old API server
  become: yes
  become_user: ckan
  command: pm2 delete all

- name: Remove PM2 dump file
  become: yes
  become_user: root
  file: path=/home/ckan/.pm2/dump.pm2 state=absent

- name: Start the API server
  become: yes
  become_user: ckan
  command: pm2 start app/app.js --name cadasta-api -- --env production
           chdir=/opt/cadasta/cadasta-api
           creates=/home/ckan/.pm2/pids/cadasta-api-0.pid

- name: Save PM2 restart state
  become: yes
  become_user: ckan
  command: pm2 save
           creates=/home/ckan/.pm2/dump.pm2
