- name: Install base CKAN OS package dependencies
  become: yes
  become_user: root
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
    - python-dev
    - postgresql-client
    - libpq-dev
    - python-pip
    - python-virtualenv
    - git-core
    - solr-tomcat
    - openjdk-6-jdk
    - python-psycopg2

- name: Create CKAN user
  become: yes
  become_user: root
  user: name=ckan

- name: Create base CKAN directory
  become: yes
  become_user: root
  file: path=/usr/lib/ckan/default state=directory owner=ckan

- name: Install base CKAN source
  become: yes
  become_user: ckan
  pip: name='git+https://github.com/ckan/ckan.git@ckan-2.4.1#egg=ckan'
       virtualenv=/usr/lib/ckan/default

- name: Install base CKAN Python dependencies
  become: yes
  become_user: ckan
  pip: requirements="/usr/lib/ckan/default/src/ckan/requirements.txt"
       virtualenv=/usr/lib/ckan/default

- name: Create /etc/ckan/default
  become: yes
  become_user: root
  file: path=/etc/ckan/default state=directory owner=ckan

- name: Link who.ini file
  become: yes
  become_user: root
  file: path=/etc/ckan/default/who.ini
        src="/usr/lib/ckan/default/src/ckan/who.ini"
        state=link
