- name: Create a sandbox EC2 instance
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Launch instance
      ec2:
        profile: cadasta
        region: us-west-2
        image: ami-5189a661
        vpc_subnet_id: subnet-08b0856d
        instance_type: t2.micro
        key_name: cadasta-utility
        group: cadasta-utility
        instance_tags: '{ "Name": "ami-builder" }'
        assign_public_ip: yes
        wait: yes
      register: ec2
    - name: Add new instance to host group
      add_host: hostname="{{ item.public_ip }}" groupname=launched
      with_items: ec2.instances
    - name: Wait for SSH to come up
      wait_for: host="{{ item.public_dns_name }}" port=22
                delay=60 timeout=320 state=started
      with_items: ec2.instances

- name: Provision EC2 instance
  hosts: launched
  remote_user: ubuntu
  gather_facts: true
  roles:
    - ckan
    - solr
    - ckan_extension
    - angular
    - api
    - ona
    - prereqs

- name: Generate machine image
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Generate machine image from running instance
      ec2_ami:
        profile: cadasta
        region: us-west-2
        instance_id: "{{ item }}"
        wait: yes
        name: "cadasta-v1.deploy.201511161115Z"
      with_items: ec2.instance_ids

- name: Terminate instance
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Terminate previously launched instance
      ec2:
        region: us-west-2
        state: absent
        instance_ids: "{{ ec2.instance_ids }}"
