- name: Create top-level installation directory
  become: yes
  become_user: root
  file: path=/opt/cadasta state=directory owner=ckan

- name: Install PostGIS
  become: yes
  become_user: root
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
    - postgis
    - postgresql-9.3-postgis-2.1
