- name: Create Postgres password file for www-data
  become: yes
  become_user: root
  copy: src=www-pgpass dest=/var/www/.pgpass owner=www-data mode=0600

- name: Set up Apache configuration
  become: yes
  become_user: root
  template: src=cadasta-apache-site
            dest=/etc/apache2/sites-available/cadasta.conf
            owner=root group=root mode=0644

- name: Set up nginx configuration
  become: yes
  become_user: root
  template: src=cadasta-nginx-site
            dest=/etc/nginx/sites-available/cadasta
            owner=root group=root mode=0644

- name: Enable Cadasta Apache site
  become: yes
  become_user: root
  shell: a2ensite cadasta

- name: Disable default Apache site
  become: yes
  become_user: root
  shell: a2dissite 000-default

- name: Disable default nginx site
  become: yes
  become_user: root
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Enable Cadasta nginx site
  become: yes
  become_user: root
  file: path=/etc/nginx/sites-enabled/cadasta
        src=/etc/nginx/sites-available/cadasta state=link

- name: (VAGRANT LOCAL ONLY) Disable Apache file compression
  become: yes
  become_user: root
  file: path=/etc/apache2/mods-enabled/deflate.load state=absent
  when: "{{ vagrant_local | default(false) }}"

- name: (VAGRANT LOCAL ONLY) Set up nginx URL rewriting
  become: yes
  become_user: root
  patch: src=nginx-vagrant.patch
         dest=/etc/nginx/sites-available/cadasta
  when: "{{ vagrant_local | default(false) }}"

- name: Restart Apache
  become: yes
  become_user: root
  service: name=apache2 state=restarted

- name: Restart nginx
  become: yes
  become_user: root
  service: name=nginx state=restarted
