- name: Install ONA OS package dependencies
  become: yes
  become_user: root
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
    - binutils
    - libproj-dev
    - gdal-bin
    - memcached
    - libmemcached-dev
    - build-essential
    - python-pip
    - python-virtualenv
    - python-dev
    - git
    - libssl-dev
    - libpq-dev
    - gfortran
    - libatlas-base-dev
    - libjpeg-dev
    - libxml2-dev
    - libxslt-dev
    - zlib1g-dev
    - python-software-properties
    - ghostscript
    - python-celery
    - python-sphinx
    - openjdk-7-jdk
    - openjdk-7-jre
    - postgresql-9.3-postgis-2.1
    - postgresql-9.3-postgis-2.1-scripts

- name: Create ONA user
  become: yes
  become_user: root
  user: name=ona

- name: Create top-level installation directory
  become: yes
  become_user: root
  file: path=/opt/ona state=directory owner=ona

- name: Clone ONA repository
  become: yes
  become_user: ona
  git: repo=https://github.com/onaio/onadata
       dest=/opt/ona/onadata

- name: Install base ONA Python dependencies
  become: yes
  become_user: ona
  pip: requirements="/opt/ona/onadata/requirements/base.pip"
       extra_args="--allow-all-external"
       virtualenv=/opt/ona/onadata

- name: Install Numpy
  become: yes
  become_user: ona
  pip: name=numpy virtualenv=/opt/ona/onadata

- name: Install Pandas
  become: yes
  become_user: ona
  pip: name=pandas version=0.12.0 virtualenv=/opt/ona/onadata

- name: Install Rabbit-MQ server
  become: yes
  become_user: root
  apt: pkg=rabbitmq-server state=present update_cache=yes

- name: Create /etc/ona/onadata
  become: yes
  become_user: root
  file: path=/etc/ona/onadata state=directory owner=ona
