- name: Install CKAN prerequisites
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
    - python-dev
    - postgresql
    - libpq-dev
    - python-pip
    - python-virtualenv
    - git-core
    - solr-jetty
    - openjdk-6-jdk
